default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  primary:
    adapter: sqlite3
    database: db/development.sqlite3
  
sendit:
  database: <%= ENV['SENDIT_DATABASE'] %>
  username: <%= ENV['SENDIT_USERNAME'] %>
  password: <%= ENV['SENDIT_PASSWORD'] %>
  adapter: sqlserver
  host: <%= ENV['SENDIT_HOST'] %>


test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  database: db/production.sqlite3
