default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  primary:
    adapter: sqlite3
    database: db/development.sqlite3
  
sendit:
  database: SendIT
  username: senditro
  password: senditro123
  adapter: sqlserver
  host: 192.168.8.53

test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  database: db/production.sqlite3
