default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  primary:
    adapter: sqlite3
    database: db/development.sqlite3
  
  sendit:
    database: SendIT
    username: sa
    password: prologis1$
    adapter: sqlserver
    host: 192.168.8.52

test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  database: db/production.sqlite3
